### ISSUE TITLE
update wasm-bindgen

### ISSUE THREAD

**Issue by tvogt** [anderejd/wasm-bindgen-minimal-example#1]
trying this out, got this error:

> 
>     Finished release [optimized] target(s) in 0.11s
> + mkdir -p html/wasm
> + wasm-bindgen target/wasm32-unknown-unknown/release/wasm_bindgen_minimal_example.wasm --out-dir html/wasm --no-modules
> error: failed to extract wasm-bindgen custom sections
> 	caused by: 
> 
> it looks like the Rust project used to create this wasm file was linked against
> a different version of wasm-bindgen than this binary:
> 
>   rust wasm file: 0.2.38
>      this binary: 0.2.40
> 
> Currently the bindgen format is unstable enough that these two version must
> exactly match, so it's required that these two version are kept in sync by
> either updating the wasm-bindgen dependency or this binary. You should be able
> to update the wasm-bindgen dependency with:
> 
>     cargo update -p wasm-bindgen
> 
> or you can update the binary with
> 
>     cargo install -f wasm-bindgen-cli
> 
> if this warning fails to go away though and you're not sure what to do feel free
> to open an issue at https://github.com/rustwasm/wasm-bindgen/issues!
> 

updating the dependency to 0.2.40 solves it.

**Comment by anderejd** [comment]
Ah yes I bumped into that problem as well, thanks for the report!

**Comment by anderejd** [comment]
Fixed by https://github.com/anderejd/wasm-bindgen-minimal-example/commit/38721ac0dbb094c9f2fb1fbd5965970674553730
